name: Weather App Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        targetplatform: [x86, x64]
    runs-on: windows-latest
    env:
      App_Packages_Directory: packages
      Solution_Path: Weather.sln
      Test_Project_Path: Weather.Providers.Tests\Weather.Providers.Tests.csproj
      Wpf_Project_Path: Weather\Weather.csproj
      Actions_Allow_Unsecure_Commands: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Nerdbank.GitVersioning to set version variables
        uses: aarnott/nbgv@v0.3
        with:
          setAllVars: true
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.302"
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Execute Unit Tests
        run: dotnet test $env:Test_Project_Path